# ===============================
# DATABASE CONFIGURATION
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/aicode_review_db
spring.datasource.username=postgres
spring.datasource.password=forever@901B

# ===============================
# JPA / HIBERNATE CONFIGURATION
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# SERVER CONFIGURATION
# ===============================
server.port=8081

spring.mvc.async.request-timeout=90000
spring.webflux.request.timeout=120s
server.tomcat.connection-timeout=120000
server.servlet.session.timeout=120s
ai.service.url=http://localhost:8000

spring.security.user.name=admin
spring.security.user.password=admin123
